<?xml version="1.0" encoding="utf-8"?><Database Class="ReadModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Rm_Contracts" Member="ContractDtos">
    <Type Name="ContractDto">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" CanBeNull="false" />
      <Column Name="SignedOn" Type="System.DateTime" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Guid" CanBeNull="false" />
      <Column Name="BorrowerId" Type="System.Int32" CanBeNull="false" />
      <Column Name="BorrowerFirstName" Type="System.String" CanBeNull="false" />
      <Column Name="BorrowerLastName" Type="System.String" CanBeNull="false" />
      <Column Name="BorrowerEmail" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Dm_Shop_Order" Member="OrderDtos">
    <Type Name="OrderDto">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" CanBeNull="false" />
      <Column Name="CreatedUtc" Storage="_CreatedOn" Type="System.DateTime" CanBeNull="false" />
      <Column Name="Status" Type="OrderStatusDto" CanBeNull="false" />
      <Column Name="Lessor_LessorId" Storage="_OrganizationId" Type="System.Guid" CanBeNull="false" />
      <Column Name="Borrower_Id" Type="System.Guid" CanBeNull="true" />
      <Column Name="Borrower_FirstName" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_LastName" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_Street" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_Postcode" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_City" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_EmailAddress" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_MobilePhoneNumber" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_MemberNumber" Type="System.String" CanBeNull="true" />
      <Column Name="ModifiedUtc" Storage="_ModifiedOn" Type="System.DateTime" CanBeNull="true" />
      <Column Name="ModifierId" Member="ModifiedBy" Type="System.Int32" CanBeNull="true" />
      <Column Name="Lessor_Name" Storage="_OrganizationName" Type="System.String" CanBeNull="false" />
      <Association Name="OrderDto_OrderItemDto" Member="Items" ThisKey="Id" OtherKey="OrderId" Type="OrderItemDto" />
      <Association Name="OrderDto_MembershipDto" Member="MembershipDtos" ThisKey="Lessor_LessorId" OtherKey="OrganizationGuid" Type="MembershipDto" />
    </Type>
  </Table>
  <Table Name="Dm_Shop_OrderItem" Member="OrderItemDtos">
    <Type Name="OrderItemDto">
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" CanBeNull="false" />
      <Column Name="FromUtc" Storage="_From" Type="System.DateTime" CanBeNull="false" />
      <Column Name="ToUtc" Storage="_To" Type="System.DateTime" CanBeNull="false" />
      <Column Name="ArticleId" Type="System.Int32" CanBeNull="false" />
      <Column Name="Total" Member="ItemTotal" Type="System.Decimal" CanBeNull="false" />
      <Association Name="OrderItemDto_OrderItemArticleDto" Member="Article" ThisKey="ArticleId" OtherKey="Id" Type="OrderItemArticleDto" Cardinality="One" />
      <Association Name="OrderDto_OrderItemDto" Member="OrderDto" ThisKey="OrderId" OtherKey="Id" Type="OrderDto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Dm_Inventory_Article" Member="OrderItemArticleDtos">
    <Type Name="OrderItemArticleDto">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" CanBeNull="false" />
      <Association Name="OrderItemDto_OrderItemArticleDto" Member="OrderItemDto" ThisKey="Id" OtherKey="ArticleId" Type="OrderItemDto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Dm_IdentityAccess_Membership" Member="MembershipDtos">
    <Type Name="MembershipDto">
      <Column Name="UserId" Type="System.Int32" CanBeNull="false" />
      <Column Name="Role" Type="MembershipRoleDto" CanBeNull="false" />
      <Column Name="OrganizationGuid" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="OrderDto_MembershipDto" Member="OrderDto" ThisKey="OrganizationGuid" OtherKey="Lessor_LessorId" Type="OrderDto" IsForeignKey="true" />
    </Type>
  </Table>
</Database>