//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phundus.Core.IdentityAccess.Users.Mails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phundus.Core.IdentityAccess.Users.Mails.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Es hat sich ein neues Mitglied auf phundus registriert. Er heisst @Model.User.DisplayName, und besitzt die J+S-Nummer @Model.User.JsNumber sowie die  E-Mailadresse @Model.User.Membership.Email.&lt;/p&gt;.
        ///
        ///&lt;p&gt;Falls ihr ihn in der NDBJS unserem Jugendverband zuordnen könnt, bestätigt seine Account im Administrationsbereich vom &quot;phundus&quot;&lt;/p&gt;..
        /// </summary>
        internal static string UserAccountCreatedHtml {
            get {
                return ResourceManager.GetString("UserAccountCreatedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzeraccount erstellt.
        /// </summary>
        internal static string UserAccountCreatedSubject {
            get {
                return ResourceManager.GetString("UserAccountCreatedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.User.FirstName&lt;/p&gt;
        ///
        ///&lt;p&gt;Du hast dich bei der Materialverleihanwendung phundus angemeldet. Bitte bestätige deine E-Mail Adresse durch das anwählen des nachfolgenden Linkes:&lt;br /&gt;&lt;a href=&quot;@Model.Urls.UserAccountValidation/@Model.User.Membership.ValidationKey&quot;&gt;@Model.Urls.UserAccountValidation/@Model.User.Membership.ValidationKey&lt;/a&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;Sollte deinen Webbrowser, diese Webseite nicht korrekt anzeigen kannst du auch @Model.Urls.UserAccountValidation in der Adresszeile eingeben und deine M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserAccountValidationHtml {
            get {
                return ResourceManager.GetString("UserAccountValidationHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validierung der E-Mail-Adresse.
        /// </summary>
        internal static string UserAccountValidationSubject {
            get {
                return ResourceManager.GetString("UserAccountValidationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.User.FirstName&lt;/p&gt;
        ///
        ///&lt;p&gt;Du hast deine E-Mailadresse bei der Materialverleihanwendung phundus geändert. Bitte bestätige deine E-Mail Adresse durch das anwählen des nachfolgenden Linkes:&lt;br /&gt;&lt;a href=&quot;@Model.Urls.UserEmailValidation/@Model.User.Membership.ValidationKey&quot;&gt;@Model.Urls.UserEmailValidation/@Model.User.Membership.ValidationKey&lt;/a&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;Sollte deinen Webbrowser, diese Webseite nicht korrekt anzeigen kannst du auch @Model.Urls.UserAccountValidation in der Adresszeile eingeben un [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserChangeEmailValidationHtml {
            get {
                return ResourceManager.GetString("UserChangeEmailValidationHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validierung der geänderten E-Mail-Adresse.
        /// </summary>
        internal static string UserChangeEmailValidationSubject {
            get {
                return ResourceManager.GetString("UserChangeEmailValidationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.User.FirstName&lt;/p&gt;
        ///
        ///&lt;p&gt; Deine phundus Account mit der E-Mail Adresse @Model.User.Membership.Email, wurde vorübergehend auf phundus gesperrt. Die aktuell eingegeben Reservationen wurden storniert. Bei Fragen zur Blockierung oder Bedingungen für eine Freischaltung solltest du dich an deine zugeteilte Organisation wenden. &lt;/p&gt;..
        /// </summary>
        internal static string UserLockedHtml {
            get {
                return ResourceManager.GetString("UserLockedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account gesperrt.
        /// </summary>
        internal static string UserLockedSubject {
            get {
                return ResourceManager.GetString("UserLockedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.User.FirstName&lt;/p&gt;
        ///
        ///&lt;p&gt;Neues Passwort ist @Model.Password.&lt;/p&gt;.
        /// </summary>
        internal static string UserResetPasswordHtml {
            get {
                return ResourceManager.GetString("UserResetPasswordHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort.
        /// </summary>
        internal static string UserResetPasswordSubject {
            get {
                return ResourceManager.GetString("UserResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.User.FirstName&lt;/p&gt;
        ///
        ///&lt;p&gt; Deine phundus Account mit der E-Mail Adresse @Model.User.Membership.Email, wurde soeben freigeschalten. Du kannst über die Anwendung nun wieder Material deiner Organisation reservieren.&lt;/p&gt;.
        ///
        ///&lt;p&gt;Viel Spass!&lt;/p&gt;.
        /// </summary>
        internal static string UserUnlockedHtml {
            get {
                return ResourceManager.GetString("UserUnlockedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account freigeschalten.
        /// </summary>
        internal static string UserUnlockedSubject {
            get {
                return ResourceManager.GetString("UserUnlockedSubject", resourceCulture);
            }
        }
    }
}
