//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phundus.Shop.Model.Mails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phundus.Shop.Model.Mails.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.Borrower.DisplayName&lt;/p&gt;
        ///
        ///&lt;p&gt;Die Bestellung vom @Model.Order.CreatedLocal mit der Nummer @Model.Order.Id wurde &lt;b&gt;genehmigt&lt;/b&gt;.&lt;/p&gt;
        ///
        ///&lt;p&gt;Bitte vereinbare mit der Materialstelle telefonisch einen Übergabetermin. Wir bitten dich bei der Materialübernahme den Mietpreis bar zu bezahlen.&lt;/p&gt;
        ///
        ///&lt;table class=&quot;table table-bordered table-striped&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Artikel&lt;/th&gt;
        ///            &lt;th&gt;Von&lt;/th&gt;
        ///            &lt;th&gt;Bis&lt;/th&gt;
        ///            &lt;th&gt;Menge&lt;/th&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderApprovedHtml {
            get {
                return ResourceManager.GetString("OrderApprovedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellung genehmigt.
        /// </summary>
        internal static string OrderApprovedSubject {
            get {
                return ResourceManager.GetString("OrderApprovedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.Borrower.DisplayName&lt;/p&gt;
        ///
        ///&lt;p&gt;Wir haben deine Bestellung vom @Model.Order.CreatedLocal mit der Nummer @Model.Order.Id erhalten.&lt;/p&gt;
        ///
        ///&lt;p&gt;Die Materialien sind im angegeben Zeitraum nun für dich reserviert. Das Sekretariat bestätigt deine Buchung vor dem Abholdatum nochmals manuell und sendet dir die abschliessende Bestellungsgenehmigung. Bitte melde dich anschliessend beim Sekretariat um einen Abholtermin zu vereinbaren&lt;/p&gt;
        ///
        ///&lt;table class=&quot;table table-bordered table-striped&quot;&gt;
        ///    &lt;thead&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderReceivedHtml {
            get {
                return ResourceManager.GetString("OrderReceivedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Bestellung.
        /// </summary>
        internal static string OrderReceivedSubject {
            get {
                return ResourceManager.GetString("OrderReceivedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hallo @Model.Borrower.DisplayName&lt;/p&gt;
        ///
        ///&lt;p&gt;Wir konnten die Bestellung vom @Model.Order.CreatedLocal mit der Nummer @Model.Order.Id infolge unvorhergesehen Ereignissen leider nicht in dem von dir eingegebenen Zeitraum freigeben.&lt;/p&gt;
        ///
        ///&lt;table class=&quot;table table-bordered table-striped&quot;&gt;
        ///    &lt;thead&gt;
        ///        &lt;tr&gt;
        ///            &lt;th&gt;Artikel&lt;/th&gt;
        ///            &lt;th&gt;Von&lt;/th&gt;
        ///            &lt;th&gt;Bis&lt;/th&gt;
        ///            &lt;th&gt;Menge&lt;/th&gt;
        ///            &lt;th&gt;Stückpreis&lt;/th&gt;
        ///            &lt;th&gt;Total&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///    &lt;/th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderRejectedHtml {
            get {
                return ResourceManager.GetString("OrderRejectedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestellung abgelehnt.
        /// </summary>
        internal static string OrderRejectedSubject {
            get {
                return ResourceManager.GetString("OrderRejectedSubject", resourceCulture);
            }
        }
    }
}
