<?xml version="1.0" encoding="utf-8"?><Database Class="ReadModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Rm_Contracts" Member="ContractDtos">
    <Type Name="ContractDto">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTime" CanBeNull="false" />
      <Column Name="SignedOn" Type="System.DateTime" CanBeNull="true" />
      <Column Name="OrganizationId" Type="System.Int32" CanBeNull="false" />
      <Column Name="BorrowerId" Type="System.Int32" CanBeNull="false" />
      <Column Name="BorrowerFirstName" Type="System.String" CanBeNull="false" />
      <Column Name="BorrowerLastName" Type="System.String" CanBeNull="false" />
      <Column Name="BorrowerEmail" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Order" Member="OrderDtos">
    <Type Name="OrderDto">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" CanBeNull="false" />
      <Column Name="CreateDate" Member="CreatedOn" Type="System.DateTime" CanBeNull="false" />
      <Column Name="Status" Type="OrderStatusDto" CanBeNull="false" />
      <Column Name="OrganizationId" Type="System.Int32" CanBeNull="false" />
      <Column Name="Borrower_Id" Type="System.Int32" CanBeNull="true" />
      <Column Name="Borrower_FirstName" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_LastName" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_Street" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_Postcode" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_City" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_EmailAddress" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_MobilePhoneNumber" Type="System.String" CanBeNull="true" />
      <Column Name="Borrower_MemberNumber" Type="System.String" CanBeNull="true" />
      <Column Name="ModifyDate" Member="ModifiedOn" Type="System.DateTime" CanBeNull="true" />
      <Column Name="ModifierId" Member="ModifiedBy" Type="System.Int32" CanBeNull="true" />
      <Association Name="OrderDto_OrderItemDto" Member="Items" ThisKey="Id" OtherKey="OrderId" Type="OrderItemDto" />
    </Type>
  </Table>
  <Table Name="OrderItem" Member="OrderItemDtos">
    <Type Name="OrderItemDto">
      <Column Name="Id" Type="System.Guid" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" CanBeNull="false" />
      <Column Name="OrderId" Type="System.Int32" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" CanBeNull="false" />
      <Column Name="From" Type="System.DateTime" CanBeNull="false" />
      <Column Name="To" Type="System.DateTime" CanBeNull="false" />
      <Column Name="ArticleId" Type="System.Int32" CanBeNull="false" />
      <Association Name="OrderDto_OrderItemDto" Member="OrderDto" ThisKey="OrderId" OtherKey="Id" Type="OrderDto" IsForeignKey="true" />
    </Type>
  </Table>
</Database>