#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phundus.Shop.Queries
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class ReadModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOrderDto(OrderDto instance);
    partial void UpdateOrderDto(OrderDto instance);
    partial void DeleteOrderDto(OrderDto instance);
    partial void InsertOrderItemDto(OrderItemDto instance);
    partial void UpdateOrderItemDto(OrderItemDto instance);
    partial void DeleteOrderItemDto(OrderItemDto instance);
    partial void InsertMembershipDto(MembershipDto instance);
    partial void UpdateMembershipDto(MembershipDto instance);
    partial void DeleteMembershipDto(MembershipDto instance);
    #endregion
		
		public ReadModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReadModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReadModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReadModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OrderDto> OrderDtos
		{
			get
			{
				return this.GetTable<OrderDto>();
			}
		}
		
		public System.Data.Linq.Table<OrderItemDto> OrderItemDtos
		{
			get
			{
				return this.GetTable<OrderItemDto>();
			}
		}
		
		public System.Data.Linq.Table<MembershipDto> MembershipDtos
		{
			get
			{
				return this.GetTable<MembershipDto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Dm_Shop_Order")]
	public partial class OrderDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Version;
		
		private System.DateTime _CreatedOn;
		
		private OrderStatusDto _Status;
		
		private System.Guid _OrganizationId;
		
		private System.Nullable<System.Guid> _Borrower_Id;
		
		private string _Borrower_FirstName;
		
		private string _Borrower_LastName;
		
		private string _Borrower_Street;
		
		private string _Borrower_Postcode;
		
		private string _Borrower_City;
		
		private string _Borrower_EmailAddress;
		
		private string _Borrower_MobilePhoneNumber;
		
		private string _Borrower_MemberNumber;
		
		private System.Nullable<System.DateTime> _ModifiedOn;
		
		private string _OrganizationName;
		
		private EntitySet<OrderItemDto> _Items;
		
		private EntitySet<MembershipDto> _MembershipDtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVersionChanging(int value);
    partial void OnVersionChanged();
    partial void OnCreatedUtcChanging(System.DateTime value);
    partial void OnCreatedUtcChanged();
    partial void OnStatusChanging(OrderStatusDto value);
    partial void OnStatusChanged();
    partial void OnLessor_LessorIdChanging(System.Guid value);
    partial void OnLessor_LessorIdChanged();
    partial void OnLessee_LesseeGuidChanging(System.Nullable<System.Guid> value);
    partial void OnLessee_LesseeGuidChanged();
    partial void OnBorrower_FirstNameChanging(string value);
    partial void OnBorrower_FirstNameChanged();
    partial void OnBorrower_LastNameChanging(string value);
    partial void OnBorrower_LastNameChanged();
    partial void OnBorrower_StreetChanging(string value);
    partial void OnBorrower_StreetChanged();
    partial void OnBorrower_PostcodeChanging(string value);
    partial void OnBorrower_PostcodeChanged();
    partial void OnBorrower_CityChanging(string value);
    partial void OnBorrower_CityChanged();
    partial void OnBorrower_EmailAddressChanging(string value);
    partial void OnBorrower_EmailAddressChanged();
    partial void OnBorrower_MobilePhoneNumberChanging(string value);
    partial void OnBorrower_MobilePhoneNumberChanged();
    partial void OnBorrower_MemberNumberChanging(string value);
    partial void OnBorrower_MemberNumberChanged();
    partial void OnModifiedUtcChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedUtcChanged();
    partial void OnLessor_NameChanging(string value);
    partial void OnLessor_NameChanged();
    #endregion
		
		public OrderDto()
		{
			this._Items = new EntitySet<OrderItemDto>(new Action<OrderItemDto>(this.attach_Items), new Action<OrderItemDto>(this.detach_Items));
			this._MembershipDtos = new EntitySet<MembershipDto>(new Action<MembershipDto>(this.attach_MembershipDtos), new Action<MembershipDto>(this.detach_MembershipDtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version")]
		public int Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn")]
		public System.DateTime CreatedUtc
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedUtcChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedUtc");
					this.OnCreatedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", CanBeNull=false)]
		public OrderStatusDto Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationId")]
		public System.Guid Lessor_LessorId
		{
			get
			{
				return this._OrganizationId;
			}
			set
			{
				if ((this._OrganizationId != value))
				{
					this.OnLessor_LessorIdChanging(value);
					this.SendPropertyChanging();
					this._OrganizationId = value;
					this.SendPropertyChanged("Lessor_LessorId");
					this.OnLessor_LessorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_Id")]
		public System.Nullable<System.Guid> Lessee_LesseeGuid
		{
			get
			{
				return this._Borrower_Id;
			}
			set
			{
				if ((this._Borrower_Id != value))
				{
					this.OnLessee_LesseeGuidChanging(value);
					this.SendPropertyChanging();
					this._Borrower_Id = value;
					this.SendPropertyChanged("Lessee_LesseeGuid");
					this.OnLessee_LesseeGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_FirstName")]
		public string Borrower_FirstName
		{
			get
			{
				return this._Borrower_FirstName;
			}
			set
			{
				if ((this._Borrower_FirstName != value))
				{
					this.OnBorrower_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._Borrower_FirstName = value;
					this.SendPropertyChanged("Borrower_FirstName");
					this.OnBorrower_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_LastName")]
		public string Borrower_LastName
		{
			get
			{
				return this._Borrower_LastName;
			}
			set
			{
				if ((this._Borrower_LastName != value))
				{
					this.OnBorrower_LastNameChanging(value);
					this.SendPropertyChanging();
					this._Borrower_LastName = value;
					this.SendPropertyChanged("Borrower_LastName");
					this.OnBorrower_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_Street")]
		public string Borrower_Street
		{
			get
			{
				return this._Borrower_Street;
			}
			set
			{
				if ((this._Borrower_Street != value))
				{
					this.OnBorrower_StreetChanging(value);
					this.SendPropertyChanging();
					this._Borrower_Street = value;
					this.SendPropertyChanged("Borrower_Street");
					this.OnBorrower_StreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_Postcode")]
		public string Borrower_Postcode
		{
			get
			{
				return this._Borrower_Postcode;
			}
			set
			{
				if ((this._Borrower_Postcode != value))
				{
					this.OnBorrower_PostcodeChanging(value);
					this.SendPropertyChanging();
					this._Borrower_Postcode = value;
					this.SendPropertyChanged("Borrower_Postcode");
					this.OnBorrower_PostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_City")]
		public string Borrower_City
		{
			get
			{
				return this._Borrower_City;
			}
			set
			{
				if ((this._Borrower_City != value))
				{
					this.OnBorrower_CityChanging(value);
					this.SendPropertyChanging();
					this._Borrower_City = value;
					this.SendPropertyChanged("Borrower_City");
					this.OnBorrower_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_EmailAddress")]
		public string Borrower_EmailAddress
		{
			get
			{
				return this._Borrower_EmailAddress;
			}
			set
			{
				if ((this._Borrower_EmailAddress != value))
				{
					this.OnBorrower_EmailAddressChanging(value);
					this.SendPropertyChanging();
					this._Borrower_EmailAddress = value;
					this.SendPropertyChanged("Borrower_EmailAddress");
					this.OnBorrower_EmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_MobilePhoneNumber")]
		public string Borrower_MobilePhoneNumber
		{
			get
			{
				return this._Borrower_MobilePhoneNumber;
			}
			set
			{
				if ((this._Borrower_MobilePhoneNumber != value))
				{
					this.OnBorrower_MobilePhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._Borrower_MobilePhoneNumber = value;
					this.SendPropertyChanged("Borrower_MobilePhoneNumber");
					this.OnBorrower_MobilePhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Borrower_MemberNumber")]
		public string Borrower_MemberNumber
		{
			get
			{
				return this._Borrower_MemberNumber;
			}
			set
			{
				if ((this._Borrower_MemberNumber != value))
				{
					this.OnBorrower_MemberNumberChanging(value);
					this.SendPropertyChanging();
					this._Borrower_MemberNumber = value;
					this.SendPropertyChanged("Borrower_MemberNumber");
					this.OnBorrower_MemberNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn")]
		public System.Nullable<System.DateTime> ModifiedUtc
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedUtcChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedUtc");
					this.OnModifiedUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationName", CanBeNull=false)]
		public string Lessor_Name
		{
			get
			{
				return this._OrganizationName;
			}
			set
			{
				if ((this._OrganizationName != value))
				{
					this.OnLessor_NameChanging(value);
					this.SendPropertyChanging();
					this._OrganizationName = value;
					this.SendPropertyChanged("Lessor_Name");
					this.OnLessor_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OrderDto_OrderItemDto", Storage="_Items", ThisKey="Id", OtherKey="OrderId")]
		public EntitySet<OrderItemDto> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OrderDto_MembershipDto", Storage="_MembershipDtos", ThisKey="Lessor_LessorId", OtherKey="OrganizationGuid")]
		public EntitySet<MembershipDto> MembershipDtos
		{
			get
			{
				return this._MembershipDtos;
			}
			set
			{
				this._MembershipDtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Items(OrderItemDto entity)
		{
			this.SendPropertyChanging();
			entity.OrderDto = this;
		}
		
		private void detach_Items(OrderItemDto entity)
		{
			this.SendPropertyChanging();
			entity.OrderDto = null;
		}
		
		private void attach_MembershipDtos(MembershipDto entity)
		{
			this.SendPropertyChanging();
			entity.OrderDto = this;
		}
		
		private void detach_MembershipDtos(MembershipDto entity)
		{
			this.SendPropertyChanging();
			entity.OrderDto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Dm_Shop_OrderItem")]
	public partial class OrderItemDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private int _Version;
		
		private int _OrderId;
		
		private int _Amount;
		
		private System.DateTime _From;
		
		private System.DateTime _To;
		
		private int _ArticleId;
		
		private decimal _ItemTotal;
		
		private string _Text;
		
		private decimal _UnitPrice;
		
		private EntityRef<OrderDto> _OrderDto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnVersionChanging(int value);
    partial void OnVersionChanged();
    partial void OnOrderIdChanging(int value);
    partial void OnOrderIdChanged();
    partial void OnAmountChanging(int value);
    partial void OnAmountChanged();
    partial void OnFromUtcChanging(System.DateTime value);
    partial void OnFromUtcChanged();
    partial void OnToUtcChanging(System.DateTime value);
    partial void OnToUtcChanged();
    partial void OnArticleIdChanging(int value);
    partial void OnArticleIdChanged();
    partial void OnItemTotalChanging(decimal value);
    partial void OnItemTotalChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnUnitPriceChanging(decimal value);
    partial void OnUnitPriceChanged();
    #endregion
		
		public OrderItemDto()
		{
			this._OrderDto = default(EntityRef<OrderDto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="OrderItemGuid", Storage="_Id", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version")]
		public int Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId")]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					if (this._OrderDto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrderIdChanging(value);
					this.SendPropertyChanging();
					this._OrderId = value;
					this.SendPropertyChanged("OrderId");
					this.OnOrderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount")]
		public int Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From")]
		public System.DateTime FromUtc
		{
			get
			{
				return this._From;
			}
			set
			{
				if ((this._From != value))
				{
					this.OnFromUtcChanging(value);
					this.SendPropertyChanging();
					this._From = value;
					this.SendPropertyChanged("FromUtc");
					this.OnFromUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To")]
		public System.DateTime ToUtc
		{
			get
			{
				return this._To;
			}
			set
			{
				if ((this._To != value))
				{
					this.OnToUtcChanging(value);
					this.SendPropertyChanging();
					this._To = value;
					this.SendPropertyChanged("ToUtc");
					this.OnToUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArticleId")]
		public int ArticleId
		{
			get
			{
				return this._ArticleId;
			}
			set
			{
				if ((this._ArticleId != value))
				{
					this.OnArticleIdChanging(value);
					this.SendPropertyChanging();
					this._ArticleId = value;
					this.SendPropertyChanged("ArticleId");
					this.OnArticleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Total", Storage="_ItemTotal")]
		public decimal ItemTotal
		{
			get
			{
				return this._ItemTotal;
			}
			set
			{
				if ((this._ItemTotal != value))
				{
					this.OnItemTotalChanging(value);
					this.SendPropertyChanging();
					this._ItemTotal = value;
					this.SendPropertyChanged("ItemTotal");
					this.OnItemTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice")]
		public decimal UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this.OnUnitPriceChanging(value);
					this.SendPropertyChanging();
					this._UnitPrice = value;
					this.SendPropertyChanged("UnitPrice");
					this.OnUnitPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OrderDto_OrderItemDto", Storage="_OrderDto", ThisKey="OrderId", OtherKey="Id", IsForeignKey=true)]
		public OrderDto OrderDto
		{
			get
			{
				return this._OrderDto.Entity;
			}
			set
			{
				OrderDto previousValue = this._OrderDto.Entity;
				if (((previousValue != value) 
							|| (this._OrderDto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OrderDto.Entity = null;
						previousValue.Items.Remove(this);
					}
					this._OrderDto.Entity = value;
					if ((value != null))
					{
						value.Items.Add(this);
						this._OrderId = value.Id;
					}
					else
					{
						this._OrderId = default(int);
					}
					this.SendPropertyChanged("OrderDto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Dm_IdentityAccess_Membership")]
	public partial class MembershipDto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserId;
		
		private MembershipRoleDto _Role;
		
		private System.Guid _OrganizationGuid;
		
		private EntityRef<OrderDto> _OrderDto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnRoleChanging(MembershipRoleDto value);
    partial void OnRoleChanged();
    partial void OnOrganizationGuidChanging(System.Guid value);
    partial void OnOrganizationGuidChanged();
    #endregion
		
		public MembershipDto()
		{
			this._OrderDto = default(EntityRef<OrderDto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UserGuid", Storage="_UserId")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", CanBeNull=false)]
		public MembershipRoleDto Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationGuid", IsPrimaryKey=true)]
		public System.Guid OrganizationGuid
		{
			get
			{
				return this._OrganizationGuid;
			}
			set
			{
				if ((this._OrganizationGuid != value))
				{
					if (this._OrderDto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrganizationGuidChanging(value);
					this.SendPropertyChanging();
					this._OrganizationGuid = value;
					this.SendPropertyChanged("OrganizationGuid");
					this.OnOrganizationGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OrderDto_MembershipDto", Storage="_OrderDto", ThisKey="OrganizationGuid", OtherKey="Lessor_LessorId", IsForeignKey=true)]
		public OrderDto OrderDto
		{
			get
			{
				return this._OrderDto.Entity;
			}
			set
			{
				OrderDto previousValue = this._OrderDto.Entity;
				if (((previousValue != value) 
							|| (this._OrderDto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OrderDto.Entity = null;
						previousValue.MembershipDtos.Remove(this);
					}
					this._OrderDto.Entity = value;
					if ((value != null))
					{
						value.MembershipDtos.Add(this);
						this._OrganizationGuid = value.Lessor_LessorId;
					}
					else
					{
						this._OrganizationGuid = default(System.Guid);
					}
					this.SendPropertyChanged("OrderDto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
